
;
;**************************************************************
;*
;*        B I O S   J U M P   T A B L E
;*
;**************************************************************
;
BOOT:   JP      0               ;NOTE WE USE FAKE DESTINATIONS
WBOOT:  JP      0
CONST:  JP      0
CONIN:  JP      0
CONOUT: JP      0
LIST:   JP      0
PUNCH:  JP      0
READER: JP      0
HOME:   JP      0
SELDSK: JP      0
SETTRK: JP      0
SETSEC: JP      0
SETDMA: JP      0
READ:   JP      0
WRITE:  JP      0
PRSTAT: JP      0
SECTRN: JP      0
