#ifndef _TOKENS_H
#define _TOKENS_H

#include <stdint.h>

extern const uint8_t *keywords[];
extern const uint8_t  num_keywords[];

enum {
    TOK_UNKNOWN = 0,

    // Directives
    TOK_DIR_FIRST = 1,
    TOK_DEFB      = 1,
    TOK_DEFS      = 2,
    TOK_DEFW      = 3,
    TOK_DEPHASE   = 4,
    TOK_END       = 5,
    TOK_EQU       = 6,
    TOK_INCBIN    = 7,
    TOK_INCLUDE   = 8,
    TOK_ORG       = 9,
    TOK_PHASE     = 10,
    TOK_DIR_LAST  = 10,

    // Instructions
    TOK_INSTR_FIRST = 11,
    TOK_ADC         = 11,
    TOK_ADD         = 12,
    TOK_AND         = 13,
    TOK_BIT         = 14,
    TOK_CALL        = 15,
    TOK_CCF         = 16,
    TOK_CP          = 17,
    TOK_CPD         = 18,
    TOK_CPDR        = 19,
    TOK_CPI         = 20,
    TOK_CPIR        = 21,
    TOK_CPL         = 22,
    TOK_DAA         = 23,
    TOK_DEC         = 24,
    TOK_DI          = 25,
    TOK_DJNZ        = 26,
    TOK_EI          = 27,
    TOK_EX          = 28,
    TOK_EXX         = 29,
    TOK_HALT        = 30,
    TOK_IM          = 31,
    TOK_IN          = 32,
    TOK_INC         = 33,
    TOK_IND         = 34,
    TOK_INDR        = 35,
    TOK_INI         = 36,
    TOK_INIR        = 37,
    TOK_JP          = 38,
    TOK_JR          = 39,
    TOK_LD          = 40,
    TOK_LDD         = 41,
    TOK_LDDR        = 42,
    TOK_LDI         = 43,
    TOK_LDIR        = 44,
    TOK_NEG         = 45,
    TOK_NOP         = 46,
    TOK_OR          = 47,
    TOK_OTDR        = 48,
    TOK_OTIR        = 49,
    TOK_OUT         = 50,
    TOK_OUTD        = 51,
    TOK_OUTI        = 52,
    TOK_POP         = 53,
    TOK_PUSH        = 54,
    TOK_RES         = 55,
    TOK_RET         = 56,
    TOK_RETI        = 57,
    TOK_RETN        = 58,
    TOK_RL          = 59,
    TOK_RLA         = 60,
    TOK_RLC         = 61,
    TOK_RLCA        = 62,
    TOK_RLD         = 63,
    TOK_RR          = 64,
    TOK_RRA         = 65,
    TOK_RRC         = 66,
    TOK_RRCA        = 67,
    TOK_RRD         = 68,
    TOK_RST         = 69,
    TOK_SBC         = 70,
    TOK_SCF         = 71,
    TOK_SET         = 72,
    TOK_SLA         = 73,
    TOK_SLL         = 74,
    TOK_SRA         = 75,
    TOK_SRL         = 76,
    TOK_SUB         = 77,
    TOK_XOR         = 78,
    TOK_INSTR_LAST  = 78,
};

#endif
