#pragma once

// Aquarius keys
enum {
    KEY_EQUALS    = 0,  // = +
    KEY_BACKSPACE = 1,  // BS Backslash
    KEY_COLON     = 2,  // : *
    KEY_RETURN    = 3,  // Return
    KEY_SEMICOLON = 4,  // ; @
    KEY_PERIOD    = 5,  // . >
    KEY_INSERT    = 6,  // Insert
    KEY_DELETE    = 7,  // Delete
    KEY_MINUS     = 8,  // - _
    KEY_SLASH     = 9,  // / ^
    KEY_0         = 10, // 0 ?
    KEY_P         = 11, // P
    KEY_L         = 12, // L
    KEY_COMMA     = 13, // , <
    KEY_UP        = 14, // Cursor up
    KEY_RIGHT     = 15, // Cursor right
    KEY_9         = 16, // 9 )
    KEY_O         = 17, // O
    KEY_K         = 18, // K
    KEY_M         = 19, // M
    KEY_N         = 20, // N
    KEY_J         = 21, // J
    KEY_LEFT      = 22, // Cursor left
    KEY_DOWN      = 23, // Cursor down
    KEY_8         = 24, // 8 (
    KEY_I         = 25, // I
    KEY_7         = 26, // 7 '
    KEY_U         = 27, // U
    KEY_H         = 28, // H
    KEY_B         = 29, // B
    KEY_HOME      = 30, // Home
    KEY_END       = 31, // End
    KEY_6         = 32, // 6 &
    KEY_Y         = 33, // Y
    KEY_G         = 34, // G
    KEY_V         = 35, // V
    KEY_C         = 36, // C
    KEY_F         = 37, // F
    KEY_PGUP      = 38, // Page Up
    KEY_PGDN      = 39, // Page Down
    KEY_5         = 40, // 5 %
    KEY_T         = 41, // T
    KEY_4         = 42, // 4 $
    KEY_R         = 43, // R
    KEY_D         = 44, // D
    KEY_X         = 45, // X
    KEY_PAUSE     = 46, // Pause/break
    KEY_PRTSCR    = 47, // PrtScr/SysRq
    KEY_3         = 48, // 3 #
    KEY_E         = 49, // E
    KEY_S         = 50, // S
    KEY_Z         = 51, // Z
    KEY_SPACE     = 52, // Space
    KEY_A         = 53, // A
    KEY_MENU      = 54, // Menu key
    KEY_TAB       = 55, // Tab
    KEY_2         = 56, // 2 "
    KEY_W         = 57, // W
    KEY_1         = 58, // 1 !
    KEY_Q         = 59, // Q
    KEY_SHIFT     = 60, // Shift
    KEY_CTRL      = 61, // Ctrl
    KEY_ALT       = 62, // Alt
    KEY_GUI       = 63, // Gui
};

#define KEY_MOD_MASK ((1ULL << KEY_SHIFT) | (1ULL << KEY_CTRL) | (1ULL << KEY_ALT) | (1ULL << KEY_GUI))
#define KEY_MASK (~KEY_MOD_MASK)

enum ScanCode {
    SCANCODE_UNKNOWN        = 0,
    SCANCODE_A              = 4,
    SCANCODE_B              = 5,
    SCANCODE_C              = 6,
    SCANCODE_D              = 7,
    SCANCODE_E              = 8,
    SCANCODE_F              = 9,
    SCANCODE_G              = 10,
    SCANCODE_H              = 11,
    SCANCODE_I              = 12,
    SCANCODE_J              = 13,
    SCANCODE_K              = 14,
    SCANCODE_L              = 15,
    SCANCODE_M              = 16,
    SCANCODE_N              = 17,
    SCANCODE_O              = 18,
    SCANCODE_P              = 19,
    SCANCODE_Q              = 20,
    SCANCODE_R              = 21,
    SCANCODE_S              = 22,
    SCANCODE_T              = 23,
    SCANCODE_U              = 24,
    SCANCODE_V              = 25,
    SCANCODE_W              = 26,
    SCANCODE_X              = 27,
    SCANCODE_Y              = 28,
    SCANCODE_Z              = 29,
    SCANCODE_1              = 30,
    SCANCODE_2              = 31,
    SCANCODE_3              = 32,
    SCANCODE_4              = 33,
    SCANCODE_5              = 34,
    SCANCODE_6              = 35,
    SCANCODE_7              = 36,
    SCANCODE_8              = 37,
    SCANCODE_9              = 38,
    SCANCODE_0              = 39,
    SCANCODE_RETURN         = 40,
    SCANCODE_ESCAPE         = 41,
    SCANCODE_BACKSPACE      = 42,
    SCANCODE_TAB            = 43,
    SCANCODE_SPACE          = 44,
    SCANCODE_MINUS          = 45,
    SCANCODE_EQUALS         = 46,
    SCANCODE_LEFTBRACKET    = 47,
    SCANCODE_RIGHTBRACKET   = 48,
    SCANCODE_BACKSLASH      = 49,
    SCANCODE_NONUSHASH      = 50,
    SCANCODE_SEMICOLON      = 51,
    SCANCODE_APOSTROPHE     = 52,
    SCANCODE_GRAVE          = 53,
    SCANCODE_COMMA          = 54,
    SCANCODE_PERIOD         = 55,
    SCANCODE_SLASH          = 56,
    SCANCODE_CAPSLOCK       = 57,
    SCANCODE_F1             = 58,
    SCANCODE_F2             = 59,
    SCANCODE_F3             = 60,
    SCANCODE_F4             = 61,
    SCANCODE_F5             = 62,
    SCANCODE_F6             = 63,
    SCANCODE_F7             = 64,
    SCANCODE_F8             = 65,
    SCANCODE_F9             = 66,
    SCANCODE_F10            = 67,
    SCANCODE_F11            = 68,
    SCANCODE_F12            = 69,
    SCANCODE_PRINTSCREEN    = 70,
    SCANCODE_SCROLLLOCK     = 71,
    SCANCODE_PAUSE          = 72,
    SCANCODE_INSERT         = 73,
    SCANCODE_HOME           = 74,
    SCANCODE_PAGEUP         = 75,
    SCANCODE_DELETE         = 76,
    SCANCODE_END            = 77,
    SCANCODE_PAGEDOWN       = 78,
    SCANCODE_RIGHT          = 79,
    SCANCODE_LEFT           = 80,
    SCANCODE_DOWN           = 81,
    SCANCODE_UP             = 82,
    SCANCODE_NUMLOCK        = 83,
    SCANCODE_KP_DIVIDE      = 84,
    SCANCODE_KP_MULTIPLY    = 85,
    SCANCODE_KP_MINUS       = 86,
    SCANCODE_KP_PLUS        = 87,
    SCANCODE_KP_ENTER       = 88,
    SCANCODE_KP_1           = 89,
    SCANCODE_KP_2           = 90,
    SCANCODE_KP_3           = 91,
    SCANCODE_KP_4           = 92,
    SCANCODE_KP_5           = 93,
    SCANCODE_KP_6           = 94,
    SCANCODE_KP_7           = 95,
    SCANCODE_KP_8           = 96,
    SCANCODE_KP_9           = 97,
    SCANCODE_KP_0           = 98,
    SCANCODE_KP_PERIOD      = 99,
    SCANCODE_NONUSBACKSLASH = 100,
    SCANCODE_APPLICATION    = 101,
    SCANCODE_LCTRL          = 224,
    SCANCODE_LSHIFT         = 225,
    SCANCODE_LALT           = 226,
    SCANCODE_LGUI           = 227,
    SCANCODE_RCTRL          = 228,
    SCANCODE_RSHIFT         = 229,
    SCANCODE_RALT           = 230,
    SCANCODE_RGUI           = 231,
    NUM_SCANCODES           = 512,
};

enum KeyMod {
    KEYMOD_NONE   = 0x0000,
    KEYMOD_LSHIFT = 0x0001,
    KEYMOD_RSHIFT = 0x0002,
    KEYMOD_LCTRL  = 0x0040,
    KEYMOD_RCTRL  = 0x0080,
    KEYMOD_LALT   = 0x0100,
    KEYMOD_RALT   = 0x0200,
    KEYMOD_LGUI   = 0x0400,
    KEYMOD_RGUI   = 0x0800,
    KEYMOD_NUM    = 0x1000,
    KEYMOD_CAPS   = 0x2000,
    KEYMOD_MODE   = 0x4000,
    KEYMOD_SCROLL = 0x8000,
    KEYMOD_CTRL   = KEYMOD_LCTRL | KEYMOD_RCTRL,
    KEYMOD_SHIFT  = KEYMOD_LSHIFT | KEYMOD_RSHIFT,
    KEYMOD_ALT    = KEYMOD_LALT | KEYMOD_RALT,
    KEYMOD_GUI    = KEYMOD_LGUI | KEYMOD_RGUI,
};
