#pragma once

enum GameCtrlBtnIdx {
    GCB_A_IDX          = 0,
    GCB_B_IDX          = 1,
    GCB_X_IDX          = 2,
    GCB_Y_IDX          = 3,
    GCB_VIEW_IDX       = 4,
    GCB_GUIDE_IDX      = 5,
    GCB_MENU_IDX       = 6,
    GCB_LS_IDX         = 7,
    GCB_RS_IDX         = 8,
    GCB_LB_IDX         = 9,
    GCB_RB_IDX         = 10,
    GCB_DPAD_UP_IDX    = 11,
    GCB_DPAD_DOWN_IDX  = 12,
    GCB_DPAD_LEFT_IDX  = 13,
    GCB_DPAD_RIGHT_IDX = 14,
    GCB_SHARE_IDX      = 15,

    GCB_A          = (1 << GCB_A_IDX),
    GCB_B          = (1 << GCB_B_IDX),
    GCB_X          = (1 << GCB_X_IDX),
    GCB_Y          = (1 << GCB_Y_IDX),
    GCB_VIEW       = (1 << GCB_VIEW_IDX),
    GCB_GUIDE      = (1 << GCB_GUIDE_IDX),
    GCB_MENU       = (1 << GCB_MENU_IDX),
    GCB_LS         = (1 << GCB_LS_IDX),
    GCB_RS         = (1 << GCB_RS_IDX),
    GCB_LB         = (1 << GCB_LB_IDX),
    GCB_RB         = (1 << GCB_RB_IDX),
    GCB_DPAD_UP    = (1 << GCB_DPAD_UP_IDX),
    GCB_DPAD_DOWN  = (1 << GCB_DPAD_DOWN_IDX),
    GCB_DPAD_LEFT  = (1 << GCB_DPAD_LEFT_IDX),
    GCB_DPAD_RIGHT = (1 << GCB_DPAD_RIGHT_IDX),
    GCB_SHARE      = (1 << GCB_SHARE_IDX),
};
