onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb/fpga_top/fpga_core/cpu/clk
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reset
add wave -noupdate /tb/fpga_top/fpga_core/cpu/bus_addr
add wave -noupdate /tb/fpga_top/fpga_core/cpu/bus_wrdata
add wave -noupdate /tb/fpga_top/fpga_core/cpu/bus_bytesel
add wave -noupdate /tb/fpga_top/fpga_core/cpu/bus_wren
add wave -noupdate /tb/fpga_top/fpga_core/cpu/bus_strobe
add wave -noupdate /tb/fpga_top/fpga_core/cpu/bus_wait
add wave -noupdate /tb/fpga_top/fpga_core/cpu/bus_rddata
add wave -noupdate /tb/fpga_top/fpga_core/cpu/irq
add wave -noupdate /tb/fpga_top/fpga_core/cpu/d_pc
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_pc
add wave -noupdate /tb/fpga_top/fpga_core/cpu/d_instr
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_instr
add wave -noupdate /tb/fpga_top/fpga_core/cpu/d_state
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_state
add wave -noupdate /tb/fpga_top/fpga_core/cpu/d_addr
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_addr
add wave -noupdate /tb/fpga_top/fpga_core/cpu/d_wrdata
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_wrdata
add wave -noupdate /tb/fpga_top/fpga_core/cpu/d_bytesel
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_bytesel
add wave -noupdate /tb/fpga_top/fpga_core/cpu/d_wren
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_wren
add wave -noupdate /tb/fpga_top/fpga_core/cpu/d_stb
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_stb
add wave -noupdate /tb/fpga_top/fpga_core/cpu/d_mstatus_mie
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_mstatus_mie
add wave -noupdate /tb/fpga_top/fpga_core/cpu/d_mstatus_mpie
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_mstatus_mpie
add wave -noupdate /tb/fpga_top/fpga_core/cpu/d_mie
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_mie
add wave -noupdate /tb/fpga_top/fpga_core/cpu/d_mtvec
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_mtvec
add wave -noupdate /tb/fpga_top/fpga_core/cpu/d_mscratch
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_mscratch
add wave -noupdate /tb/fpga_top/fpga_core/cpu/d_mepc
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_mepc
add wave -noupdate /tb/fpga_top/fpga_core/cpu/d_mcause_irq
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_mcause_irq
add wave -noupdate /tb/fpga_top/fpga_core/cpu/d_mcause_code
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_mcause_code
add wave -noupdate /tb/fpga_top/fpga_core/cpu/d_mtval
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_mtval
add wave -noupdate /tb/fpga_top/fpga_core/cpu/d_mip
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_mip
add wave -noupdate /tb/fpga_top/fpga_core/cpu/opcode
add wave -noupdate /tb/fpga_top/fpga_core/cpu/funct3
add wave -noupdate /tb/fpga_top/fpga_core/cpu/funct7
add wave -noupdate /tb/fpga_top/fpga_core/cpu/rs1_idx
add wave -noupdate /tb/fpga_top/fpga_core/cpu/rs2_idx
add wave -noupdate /tb/fpga_top/fpga_core/cpu/rd_idx
add wave -noupdate /tb/fpga_top/fpga_core/cpu/imm_i
add wave -noupdate /tb/fpga_top/fpga_core/cpu/imm_s
add wave -noupdate /tb/fpga_top/fpga_core/cpu/imm_b
add wave -noupdate /tb/fpga_top/fpga_core/cpu/imm_u
add wave -noupdate /tb/fpga_top/fpga_core/cpu/imm_j
add wave -noupdate /tb/fpga_top/fpga_core/cpu/csr
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_lui
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_auipc
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_jal
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_jalr
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_branch
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_load
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_store
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_alu_imm
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_alu_reg
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_system
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_fence
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_ecall
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_ebreak
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_mret
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_csr
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_valid_instruction
add wave -noupdate /tb/fpga_top/fpga_core/cpu/rd_data
add wave -noupdate /tb/fpga_top/fpga_core/cpu/rd_wr
add wave -noupdate /tb/fpga_top/fpga_core/cpu/regfile
add wave -noupdate /tb/fpga_top/fpga_core/cpu/rs1_data
add wave -noupdate /tb/fpga_top/fpga_core/cpu/rs2_data
add wave -noupdate /tb/fpga_top/fpga_core/cpu/rs2_data_s
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg0_zero
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg1_ra
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg2_sp
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg3_gp
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg4_tp
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg5_t0
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg6_t1
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg7_t2
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg8_s0_fp
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg9_s1
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg10_a0
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg11_a1
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg12_a2
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg13_a3
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg14_a4
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg15_a5
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg16_a6
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg17_a7
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg18_s2
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg19_s3
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg20_s4
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg21_s5
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg22_s6
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg23_s7
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg24_s8
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg25_s9
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg26_s10
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg27_s11
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg28_t3
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg29_t4
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg30_t5
add wave -noupdate /tb/fpga_top/fpga_core/cpu/reg31_t6
add wave -noupdate /tb/fpga_top/fpga_core/cpu/i
add wave -noupdate /tb/fpga_top/fpga_core/cpu/l_operand
add wave -noupdate /tb/fpga_top/fpga_core/cpu/r_operand
add wave -noupdate /tb/fpga_top/fpga_core/cpu/shamt
add wave -noupdate /tb/fpga_top/fpga_core/cpu/alu_add
add wave -noupdate /tb/fpga_top/fpga_core/cpu/alu_sub
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_eq
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_lt
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_ltu
add wave -noupdate /tb/fpga_top/fpga_core/cpu/shl0
add wave -noupdate /tb/fpga_top/fpga_core/cpu/shl1
add wave -noupdate /tb/fpga_top/fpga_core/cpu/shl2
add wave -noupdate /tb/fpga_top/fpga_core/cpu/shl4
add wave -noupdate /tb/fpga_top/fpga_core/cpu/shl8
add wave -noupdate /tb/fpga_top/fpga_core/cpu/shl16
add wave -noupdate /tb/fpga_top/fpga_core/cpu/shr_msb
add wave -noupdate /tb/fpga_top/fpga_core/cpu/shr0
add wave -noupdate /tb/fpga_top/fpga_core/cpu/shr1
add wave -noupdate /tb/fpga_top/fpga_core/cpu/shr2
add wave -noupdate /tb/fpga_top/fpga_core/cpu/shr4
add wave -noupdate /tb/fpga_top/fpga_core/cpu/shr8
add wave -noupdate /tb/fpga_top/fpga_core/cpu/shr16
add wave -noupdate /tb/fpga_top/fpga_core/cpu/mult_l
add wave -noupdate /tb/fpga_top/fpga_core/cpu/mult_r
add wave -noupdate /tb/fpga_top/fpga_core/cpu/mult_result
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_mul_div
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_div_rem
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_quotient
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_remainder
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_div_busy
add wave -noupdate /tb/fpga_top/fpga_core/cpu/div_start
add wave -noupdate /tb/fpga_top/fpga_core/cpu/div_is_signed
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_div_dividend
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_div_divisor
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_div_quotient
add wave -noupdate /tb/fpga_top/fpga_core/cpu/q_div_quotient_msk
add wave -noupdate /tb/fpga_top/fpga_core/cpu/alu_result
add wave -noupdate /tb/fpga_top/fpga_core/cpu/load_store_addr
add wave -noupdate /tb/fpga_top/fpga_core/cpu/do_branch
add wave -noupdate /tb/fpga_top/fpga_core/cpu/lb_data
add wave -noupdate /tb/fpga_top/fpga_core/cpu/lh_data
add wave -noupdate /tb/fpga_top/fpga_core/cpu/load_data
add wave -noupdate /tb/fpga_top/fpga_core/cpu/bus_rddata_s
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_mstatus
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_mie
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_mtvec
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_mscratch
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_mepc
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_mcause
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_mtval
add wave -noupdate /tb/fpga_top/fpga_core/cpu/is_mip
add wave -noupdate /tb/fpga_top/fpga_core/cpu/mstatus
add wave -noupdate /tb/fpga_top/fpga_core/cpu/csr_rdata
add wave -noupdate /tb/fpga_top/fpga_core/cpu/csr_operand
add wave -noupdate /tb/fpga_top/fpga_core/cpu/csr_wdata
add wave -noupdate /tb/fpga_top/fpga_core/cpu/csr_write
add wave -noupdate /tb/fpga_top/fpga_core/cpu/irq_code
add wave -noupdate /tb/fpga_top/fpga_core/cpu/irq_pending
add wave -noupdate /tb/fpga_top/fpga_core/cpu/pc_plus4
add wave -noupdate /tb/fpga_top/fpga_core/cpu/pc_plus_imm
add wave -noupdate /tb/fpga_top/fpga_core/cpu/do_trap
add wave -noupdate /tb/fpga_top/fpga_core/cpu/trap_is_irq
add wave -noupdate /tb/fpga_top/fpga_core/cpu/trap_code
add wave -noupdate /tb/fpga_top/fpga_core/cpu/trap_mtval
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {73272998 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 399
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {98441406 ps} {99988496 ps}
