M48
; DRILL file {KiCad (6.0.4-0)} date 2022 April 09, Saturday 07:25:16
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-09T07:25:16+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.200
%
G90
G05
T1
X84.5Y-127.325
T2
X105.5Y-127.325
T3
X68.5Y-49.0
X68.5Y-64.0
X68.5Y-79.0
X75.5Y-49.0
X75.5Y-64.0
X75.5Y-79.0
X125.0Y-38.5
X125.0Y-45.5
T4
X69.0Y-39.0
X69.0Y-146.0
X221.0Y-39.0
X221.0Y-146.0
T0
M30
