#pragma once

enum {
    IOPIN_LED         = 4,
    IOPIN_SD_WP_N     = 5,
    IOPIN_SD_CD_N     = 6,
    IOPIN_SD_MISO     = 7,
    IOPIN_SD_SCK      = 15,
    IOPIN_SD_MOSI     = 16,
    IOPIN_SD_SSEL_N   = 17,
    IOPIN_FPGA_DONE   = 8,
    IOPIN_USB_DM      = 19,
    IOPIN_USB_DP      = 20,
    IOPIN_SPI_MISO    = 11,
    IOPIN_SPI_MOSI    = 9,
    IOPIN_SPI_SCLK    = 10,
    IOPIN_SPI_CS_N    = 3,
    IOPIN_ESP_NOTIFY  = 12,
    IOPIN_ESP_TX      = 13,
    IOPIN_ESP_RTS     = 14,
    IOPIN_ESP_RX      = 21,
    IOPIN_ESP_CTS     = 47,
    IOPIN_FPGA_PROG_N = 48,
    IOPIN_DBG_TXD0    = 43,
    IOPIN_DBG_RXD0    = 44,
    IOPIN_ESP_EXP0    = 1,
    IOPIN_ESP_EXP1    = 2,
    IOPIN_ESP_EXP2    = 42,
    IOPIN_ESP_EXP3    = 41,
    IOPIN_ESP_EXP4    = 40,
    IOPIN_ESP_EXP5    = 39,
    IOPIN_ESP_EXP6    = 38,
    IOPIN_ESP_EXP7    = 37,
    IOPIN_ESP_EXP8    = 36,
    IOPIN_ESP_EXP9    = 35,
    IOPIN_ESP_EXP10   = 18,
};
